#define USB_SUSPEND_WAKEUP_DELAY 0
#define SERIAL_NUMBER "GeMxQ/wO3ZLd"
#define LAYER_STATE_8BIT

#define WHEEL_EXTENDED_SUPPORT
#define POINTING_DEVICE_HIRES_SCROLL_ENABLE
#define POINTING_DEVICE_HIRES_SCROLL_EXPONENT 1
#define POINTING_DEVICE_GESTURES_CURSOR_GLIDE_ENABLE
#define MOUSE_EXTENDED_REPORT
#define NAVIGATOR_TRACKBALL_CPI 40
#define NAVIGATOR_SCROLL_DIVIDER 75

#define RGB_MATRIX_STARTUP_SPD 60

